fix: Ember is not defined error
miguelcobain/ember-paper pull request #1240
Opened 2023-05-29 11:03 UTC by wozny1989

# Tasks:
 - [x] Fix error `Ember is not defined` - import Ember during library version register
 - [x] Fix `@ember/jquery` issue https://github.com/emberjs/ember-jquery/issues/478

2023-05-29 13:25 UTC, Rxbsxn approved these changes

2023-06-07 09:18 UTC, mansona requested changes
So I don't think we should probably do these changes 🙈 I understand that you're trying to fix something here but I would rather a) just plainly remove the functionality b) fix it upstream or c) upgrade to more standard ways of doing it.

I hope all that makes sense?

2023-06-07 09:18 UTC, mansona commented on index.js
> +      `const Ember = require('ember').default;Ember.libraries.register('Ember Paper', '${version}');`
I think I would prefer just to remove this functionality 🤔 I don't think we need to define the Ember-Paper version in the client side for any good reason

2023-06-07 09:18 UTC, mansona commented on package.json
> +    "postinstall": "patch-package"
we really can't be adding a patch-package post install to this 🙈

2023-06-07 09:18 UTC, mansona commented on package.json
> +    "@ember/jquery": "2.0.0",
we should probably be removing `@ember/jquery`. Is there anything useful that it's actually being used for?

2023-06-10 18:24 UTC, wozny1989 commented
@mansona You're right, I just removed functionality with register version if is no super required 👍

2023-06-14 08:49 UTC, mansona approved these changes
looks great 🎉

2023-06-14 08:50 UTC, merged